# Script simple para corregir codificación en blog-detail-legends.html
$file = "blog-detail-legends.html"

Write-Host "Corrigiendo codificación en $file..." -ForegroundColor Yellow

# Leer contenido
$content = Get-Content $file -Raw -Encoding UTF8

# Correcciones específicas encontradas
$content = $content -replace 'fútbol', 'fútbol'
$content = $content -replace 'Pelé', 'Pelé'
$content = $content -replace 'Más', 'Más'
$content = $content -replace '¿viste', '¿viste'
$content = $content -replace 'poesía', 'poesía'
$content = $content -replace 'sillón', 'sillón'
$content = $content -replace 'más', 'más'
$content = $content -replace '¡Un', '¡Un'
$content = $content -replace 'sinónimo', 'sinónimo'
$content = $content -replace 'único', 'único'
$content = $content -replace 'ganó', 'ganó'
$content = $content -replace '¡TRE-S', '¡TRE-S'
$content = $content -replace 'hacía', 'hacía'
$content = $content -replace '¡un', '¡un'
$content = $content -replace '¡mil', '¡mil'
$content = $content -replace 'después', 'después'
$content = $content -replace 'cómo', 'cómo'
$content = $content -replace 'rebeldía', 'rebeldía'
$content = $content -replace 'conquistó', 'conquistó'
$content = $content -replace 'México', 'México'
$content = $content -replace '¡Eso', '¡Eso'
$content = $content -replace 'Llevó', 'Llevó'
$content = $content -replace 'títulos', 'títulos'
$content = $content -replace 'polémico', 'polémico'
$content = $content -replace 'cósmico', 'cósmico'
$content = $content -replace '¡Gracias', '¡Gracias'
$content = $content -replace 'Revolucionó', 'Revolucionó'
$content = $content -replace 'Mecánica', 'Mecánica'
$content = $content -replace 'selección', 'selección'
$content = $content -replace 'enamoró', 'enamoró'
$content = $content -replace '¡mamita', '¡mamita'
$content = $content -replace 'sinfonía', 'sinfonía'
$content = $content -replace 'armó', 'armó'
$content = $content -replace 'sentó', 'sentó'
$content = $content -replace '¿Qué', '¿Qué'
$content = $content -replace 'Andrés', 'Andrés'
$content = $content -replace '¡siete', '¡siete'
$content = $content -replace 'dio', 'dio'
$content = $content -replace '¡por', '¡por'
$content = $content -replace 'campeón', 'campeón'
$content = $content -replace 'cerró', 'cerró'
$content = $content -replace 'círculo', 'círculo'
$content = $content -replace 'recién', 'recién'
$content = $content -replace 'reinventándose', 'reinventándose'
$content = $content -replace 'día', 'día'
$content = $content -replace 'ambición', 'ambición'
$content = $content -replace 'empezó', 'empezó'
$content = $content -replace 'convirtió', 'convirtió'
$content = $content -replace 'siguió', 'siguió'
$content = $content -replace 'histórico', 'histórico'
$content = $content -replace 'increíble', 'increíble'
$content = $content -replace 'marcó', 'marcó'
$content = $content -replace 'época', 'época'
$content = $content -replace 'dominó', 'dominó'
$content = $content -replace 'completísimo', 'completísimo'
$content = $content -replace 'defendía', 'defendía'
$content = $content -replace 'metía', 'metía'
$content = $content -replace 'Lideró', 'Lideró'
$content = $content -replace 'Nazário', 'Nazário'
$content = $content -replace 'Fenómeno', 'Fenómeno'
$content = $content -replace 'superó', 'superó'
$content = $content -replace 'alegría', 'alegría'
$content = $content -replace 'fantasía', 'fantasía'
$content = $content -replace 'ángel', 'ángel'
$content = $content -replace 'Puskás', 'Puskás'
$content = $content -replace 'Cañoncito', 'Cañoncito'
$content = $content -replace 'mágica', 'mágica'
$content = $content -replace 'Eusébio', 'Eusébio'
$content = $content -replace 'Müller', 'Müller'
$content = $content -replace 'inspiración', 'inspiración'
$content = $content -replace 'sueñan', 'sueñan'
$content = $content -replace 'ídolos', 'ídolos'
$content = $content -replace '¡Salud', '¡Salud'
$content = $content -replace 'Artículos', 'Artículos'
$content = $content -replace 'panorámica', 'panorámica'
$content = $content -replace 'Evolución', 'Evolución'
$content = $content -replace 'Artículo', 'Artículo'

# Guardar archivo
$content | Out-File $file -Encoding UTF8 -NoNewline

Write-Host "Codificación corregida exitosamente" -ForegroundColor Green 
$file = "blog-detail-legends.html"

Write-Host "Corrigiendo codificación en $file..." -ForegroundColor Yellow

# Leer contenido
$content = Get-Content $file -Raw -Encoding UTF8

# Correcciones específicas encontradas
$content = $content -replace 'fútbol', 'fútbol'
$content = $content -replace 'Pelé', 'Pelé'
$content = $content -replace 'Más', 'Más'
$content = $content -replace '¿viste', '¿viste'
$content = $content -replace 'poesía', 'poesía'
$content = $content -replace 'sillón', 'sillón'
$content = $content -replace 'más', 'más'
$content = $content -replace '¡Un', '¡Un'
$content = $content -replace 'sinónimo', 'sinónimo'
$content = $content -replace 'único', 'único'
$content = $content -replace 'ganó', 'ganó'
$content = $content -replace '¡TRE-S', '¡TRE-S'
$content = $content -replace 'hacía', 'hacía'
$content = $content -replace '¡un', '¡un'
$content = $content -replace '¡mil', '¡mil'
$content = $content -replace 'después', 'después'
$content = $content -replace 'cómo', 'cómo'
$content = $content -replace 'rebeldía', 'rebeldía'
$content = $content -replace 'conquistó', 'conquistó'
$content = $content -replace 'México', 'México'
$content = $content -replace '¡Eso', '¡Eso'
$content = $content -replace 'Llevó', 'Llevó'
$content = $content -replace 'títulos', 'títulos'
$content = $content -replace 'polémico', 'polémico'
$content = $content -replace 'cósmico', 'cósmico'
$content = $content -replace '¡Gracias', '¡Gracias'
$content = $content -replace 'Revolucionó', 'Revolucionó'
$content = $content -replace 'Mecánica', 'Mecánica'
$content = $content -replace 'selección', 'selección'
$content = $content -replace 'enamoró', 'enamoró'
$content = $content -replace '¡mamita', '¡mamita'
$content = $content -replace 'sinfonía', 'sinfonía'
$content = $content -replace 'armó', 'armó'
$content = $content -replace 'sentó', 'sentó'
$content = $content -replace '¿Qué', '¿Qué'
$content = $content -replace 'Andrés', 'Andrés'
$content = $content -replace '¡siete', '¡siete'
$content = $content -replace 'dio', 'dio'
$content = $content -replace '¡por', '¡por'
$content = $content -replace 'campeón', 'campeón'
$content = $content -replace 'cerró', 'cerró'
$content = $content -replace 'círculo', 'círculo'
$content = $content -replace 'recién', 'recién'
$content = $content -replace 'reinventándose', 'reinventándose'
$content = $content -replace 'día', 'día'
$content = $content -replace 'ambición', 'ambición'
$content = $content -replace 'empezó', 'empezó'
$content = $content -replace 'convirtió', 'convirtió'
$content = $content -replace 'siguió', 'siguió'
$content = $content -replace 'histórico', 'histórico'
$content = $content -replace 'increíble', 'increíble'
$content = $content -replace 'marcó', 'marcó'
$content = $content -replace 'época', 'época'
$content = $content -replace 'dominó', 'dominó'
$content = $content -replace 'completísimo', 'completísimo'
$content = $content -replace 'defendía', 'defendía'
$content = $content -replace 'metía', 'metía'
$content = $content -replace 'Lideró', 'Lideró'
$content = $content -replace 'Nazário', 'Nazário'
$content = $content -replace 'Fenómeno', 'Fenómeno'
$content = $content -replace 'superó', 'superó'
$content = $content -replace 'alegría', 'alegría'
$content = $content -replace 'fantasía', 'fantasía'
$content = $content -replace 'ángel', 'ángel'
$content = $content -replace 'Puskás', 'Puskás'
$content = $content -replace 'Cañoncito', 'Cañoncito'
$content = $content -replace 'mágica', 'mágica'
$content = $content -replace 'Eusébio', 'Eusébio'
$content = $content -replace 'Müller', 'Müller'
$content = $content -replace 'inspiración', 'inspiración'
$content = $content -replace 'sueñan', 'sueñan'
$content = $content -replace 'ídolos', 'ídolos'
$content = $content -replace '¡Salud', '¡Salud'
$content = $content -replace 'Artículos', 'Artículos'
$content = $content -replace 'panorámica', 'panorámica'
$content = $content -replace 'Evolución', 'Evolución'
$content = $content -replace 'Artículo', 'Artículo'

# Guardar archivo
$content | Out-File $file -Encoding UTF8 -NoNewline

Write-Host "Codificación corregida exitosamente" -ForegroundColor Green 