# Script final para corregir caracteres corruptos en blog-detail-legends.html
$file = "blog-detail-legends.html"

Write-Host "Corrigiendo caracteres corruptos en $file..." -ForegroundColor Yellow

# Leer contenido
$content = Get-Content $file -Raw -Encoding UTF8

Write-Host "Aplicando correcciones..." -ForegroundColor Green

# Correcciones de caracteres corruptos
$content = $content -replace 'f�tbol', 'fútbol'
$content = $content -replace 'Pel�', 'Pelé'
$content = $content -replace 'M�s', 'Más'
$content = $content -replace '�viste', '¿viste'
$content = $content -replace 'poes�a', 'poesía'
$content = $content -replace 'sill�n', 'sillón'
$content = $content -replace 'm�s', 'más'
$content = $content -replace '�Un', '¡Un'
$content = $content -replace 'sin�nimo', 'sinónimo'
$content = $content -replace '�nico', 'único'
$content = $content -replace 'gan�', 'ganó'
$content = $content -replace '�TRE-S', '¡TRE-S'
$content = $content -replace 'hac�a', 'hacía'
$content = $content -replace 'despu�s', 'después'
$content = $content -replace 'c�mo', 'cómo'
$content = $content -replace 'rebeld�a', 'rebeldía'
$content = $content -replace 'conquist�', 'conquistó'
$content = $content -replace 'M�xico', 'México'
$content = $content -replace '�Eso', '¡Eso'
$content = $content -replace 'Llev�', 'Llevó'
$content = $content -replace 't�tulos', 'títulos'
$content = $content -replace 'pol�mico', 'polémico'
$content = $content -replace 'c�smico', 'cósmico'
$content = $content -replace '�Gracias', '¡Gracias'
$content = $content -replace 'Revolucion�', 'Revolucionó'
$content = $content -replace 'F�tbol', 'Fútbol'
$content = $content -replace 'Mec�nica', 'Mecánica'
$content = $content -replace 'selecci�n', 'selección'
$content = $content -replace 'enamor�', 'enamoró'
$content = $content -replace '�mamita', '¡mamita'
$content = $content -replace 'Gan�', 'Ganó'
$content = $content -replace 'sinfon�a', 'sinfonía'
$content = $content -replace 'Despu�s', 'Después'
$content = $content -replace 'rompi�', 'rompió'
$content = $content -replace 't�cnico', 'técnico'
$content = $content -replace 'arm�', 'armó'
$content = $content -replace 'sent�', 'sentó'
$content = $content -replace '�Qu�', '¿Qué'
$content = $content -replace 'Andr�s', 'Andrés'
$content = $content -replace '�siete', '¡siete'
$content = $content -replace 'di�', 'dio'
$content = $content -replace '�por', '¡por'
$content = $content -replace 'campe�n', 'campeón'
$content = $content -replace 'cerr�', 'cerró'
$content = $content -replace 'c�rculo', 'círculo'
$content = $content -replace 'reci�n', 'recién'
$content = $content -replace 'reinvent�ndose', 'reinventándose'
$content = $content -replace 'd�a', 'día'
$content = $content -replace 'ambici�n', 'ambición'
$content = $content -replace 'empez�', 'empezó'
$content = $content -replace 'convirti�', 'convirtió'
$content = $content -replace 'sigui�', 'siguió'
$content = $content -replace 'hist�rico', 'histórico'
$content = $content -replace 'incre�ble', 'increíble'
$content = $content -replace 'marc�', 'marcó'
$content = $content -replace '�poca', 'época'
$content = $content -replace 'domin�', 'dominó'
$content = $content -replace 'complet�simo', 'completísimo'
$content = $content -replace 'defend�a', 'defendía'
$content = $content -replace 'met�a', 'metía'
$content = $content -replace '�un', '¡un'
$content = $content -replace 'Lider�', 'Lideró'
$content = $content -replace 't�ctica', 'táctica'
$content = $content -replace 'cambi�', 'cambió'
$content = $content -replace 'Naz�rio', 'Nazário'
$content = $content -replace 'Fen�meno', 'Fenómeno'
$content = $content -replace 'super�', 'superó'
$content = $content -replace 'alegr�a', 'alegría'
$content = $content -replace 'fantas�a', 'fantasía'
$content = $content -replace '�ngel', 'ángel'
$content = $content -replace 'Pusk�s', 'Puskás'
$content = $content -replace 'Ca�oncito', 'Cañoncito'
$content = $content -replace 'm�gica', 'mágica'
$content = $content -replace 'Eus�bio', 'Eusébio'
$content = $content -replace 'M�ller', 'Müller'
$content = $content -replace 'inspiraci�n', 'inspiración'
$content = $content -replace 'sue�an', 'sueñan'
$content = $content -replace '�dolos', 'ídolos'
$content = $content -replace '�Salud', '¡Salud'
$content = $content -replace 'panor�mica', 'panorámica'
$content = $content -replace 'Art�culos', 'Artículos'
$content = $content -replace 'Evoluci�n', 'Evolución'
$content = $content -replace 'agarr�', 'agarró'
$content = $content -replace 'par�', 'paró'
$content = $content -replace 'met�', 'metió'
$content = $content -replace 'Jug�', 'Jugó'
$content = $content -replace 'haza�as', 'hazañas'
$content = $content -replace '�mil', '¡mil'
$content = $content -replace 'St�fano', 'Stéfano'
$content = $content -replace 'Toc�', 'Tocó'
$content = $content -replace 'C�smico', 'Cósmico'

# Guardar archivo
$content | Out-File $file -Encoding UTF8 -NoNewline

Write-Host "Correcciones aplicadas exitosamente!" -ForegroundColor Green 
$file = "blog-detail-legends.html"

Write-Host "Corrigiendo caracteres corruptos en $file..." -ForegroundColor Yellow

# Leer contenido
$content = Get-Content $file -Raw -Encoding UTF8

Write-Host "Aplicando correcciones..." -ForegroundColor Green

# Correcciones de caracteres corruptos
$content = $content -replace 'f�tbol', 'fútbol'
$content = $content -replace 'Pel�', 'Pelé'
$content = $content -replace 'M�s', 'Más'
$content = $content -replace '�viste', '¿viste'
$content = $content -replace 'poes�a', 'poesía'
$content = $content -replace 'sill�n', 'sillón'
$content = $content -replace 'm�s', 'más'
$content = $content -replace '�Un', '¡Un'
$content = $content -replace 'sin�nimo', 'sinónimo'
$content = $content -replace '�nico', 'único'
$content = $content -replace 'gan�', 'ganó'
$content = $content -replace '�TRE-S', '¡TRE-S'
$content = $content -replace 'hac�a', 'hacía'
$content = $content -replace 'despu�s', 'después'
$content = $content -replace 'c�mo', 'cómo'
$content = $content -replace 'rebeld�a', 'rebeldía'
$content = $content -replace 'conquist�', 'conquistó'
$content = $content -replace 'M�xico', 'México'
$content = $content -replace '�Eso', '¡Eso'
$content = $content -replace 'Llev�', 'Llevó'
$content = $content -replace 't�tulos', 'títulos'
$content = $content -replace 'pol�mico', 'polémico'
$content = $content -replace 'c�smico', 'cósmico'
$content = $content -replace '�Gracias', '¡Gracias'
$content = $content -replace 'Revolucion�', 'Revolucionó'
$content = $content -replace 'F�tbol', 'Fútbol'
$content = $content -replace 'Mec�nica', 'Mecánica'
$content = $content -replace 'selecci�n', 'selección'
$content = $content -replace 'enamor�', 'enamoró'
$content = $content -replace '�mamita', '¡mamita'
$content = $content -replace 'Gan�', 'Ganó'
$content = $content -replace 'sinfon�a', 'sinfonía'
$content = $content -replace 'Despu�s', 'Después'
$content = $content -replace 'rompi�', 'rompió'
$content = $content -replace 't�cnico', 'técnico'
$content = $content -replace 'arm�', 'armó'
$content = $content -replace 'sent�', 'sentó'
$content = $content -replace '�Qu�', '¿Qué'
$content = $content -replace 'Andr�s', 'Andrés'
$content = $content -replace '�siete', '¡siete'
$content = $content -replace 'di�', 'dio'
$content = $content -replace '�por', '¡por'
$content = $content -replace 'campe�n', 'campeón'
$content = $content -replace 'cerr�', 'cerró'
$content = $content -replace 'c�rculo', 'círculo'
$content = $content -replace 'reci�n', 'recién'
$content = $content -replace 'reinvent�ndose', 'reinventándose'
$content = $content -replace 'd�a', 'día'
$content = $content -replace 'ambici�n', 'ambición'
$content = $content -replace 'empez�', 'empezó'
$content = $content -replace 'convirti�', 'convirtió'
$content = $content -replace 'sigui�', 'siguió'
$content = $content -replace 'hist�rico', 'histórico'
$content = $content -replace 'incre�ble', 'increíble'
$content = $content -replace 'marc�', 'marcó'
$content = $content -replace '�poca', 'época'
$content = $content -replace 'domin�', 'dominó'
$content = $content -replace 'complet�simo', 'completísimo'
$content = $content -replace 'defend�a', 'defendía'
$content = $content -replace 'met�a', 'metía'
$content = $content -replace '�un', '¡un'
$content = $content -replace 'Lider�', 'Lideró'
$content = $content -replace 't�ctica', 'táctica'
$content = $content -replace 'cambi�', 'cambió'
$content = $content -replace 'Naz�rio', 'Nazário'
$content = $content -replace 'Fen�meno', 'Fenómeno'
$content = $content -replace 'super�', 'superó'
$content = $content -replace 'alegr�a', 'alegría'
$content = $content -replace 'fantas�a', 'fantasía'
$content = $content -replace '�ngel', 'ángel'
$content = $content -replace 'Pusk�s', 'Puskás'
$content = $content -replace 'Ca�oncito', 'Cañoncito'
$content = $content -replace 'm�gica', 'mágica'
$content = $content -replace 'Eus�bio', 'Eusébio'
$content = $content -replace 'M�ller', 'Müller'
$content = $content -replace 'inspiraci�n', 'inspiración'
$content = $content -replace 'sue�an', 'sueñan'
$content = $content -replace '�dolos', 'ídolos'
$content = $content -replace '�Salud', '¡Salud'
$content = $content -replace 'panor�mica', 'panorámica'
$content = $content -replace 'Art�culos', 'Artículos'
$content = $content -replace 'Evoluci�n', 'Evolución'
$content = $content -replace 'agarr�', 'agarró'
$content = $content -replace 'par�', 'paró'
$content = $content -replace 'met�', 'metió'
$content = $content -replace 'Jug�', 'Jugó'
$content = $content -replace 'haza�as', 'hazañas'
$content = $content -replace '�mil', '¡mil'
$content = $content -replace 'St�fano', 'Stéfano'
$content = $content -replace 'Toc�', 'Tocó'
$content = $content -replace 'C�smico', 'Cósmico'

# Guardar archivo
$content | Out-File $file -Encoding UTF8 -NoNewline

Write-Host "Correcciones aplicadas exitosamente!" -ForegroundColor Green 