services:
  - type: web
    name: cracktotal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8081
    domains:
      - cracktotal.com
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: geolocation=(), microphone=(), camera=()
    redirects:
      - source: /index.html
        destination: /
        type: permanent
      - source: www.cracktotal.com/*
        destination: https://cracktotal.com/:splat
        type: permanent 